version: "3.9"
services:
  deploy:
    depends_on:
      - postgres
    container_name: deploySberTestProject
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sberTestTask:5432/sber_test_task_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
  postgres:
    container_name: sberTestTask
    image: postgres
    environment:
      POSTGRES_DB: "sber_test_task_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432"
